name = "CL"
uuid = "f25cb794-9083-11e8-0aef-7ba1ed0dc970"
authors = ["David Ellison <davidehellison@gmail.com>"]
version = "0.1.0"

[deps]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]